# Neural Networks

In this exercise you will learn how to implement a feedforward <b style="color:lightgreen">neural network</b> and train it with backpropagation.

In [1]:
import numpy as np
from numpy.random import multivariate_normal
from numpy.random import uniform
from scipy.stats import zscore

We define two helper functions `init_toy_data()` and `init_model()` to create a simple <b style="color:Brown">data set</b> to work on and a <b style="color:lightgreen">2 layer neural network</b>. 

### Helper function `init_toy_data(num_samples, num_features, num_classes, seed=3)`

First, we create <b style="color:RawSienna">toy data</b> with categorical labels by sampling from different multivariate <b style="color:Cornflowerblue">normal distributions</b> for each class(one entry of the class label vector $\mathbf{\color{Dandelion}y}$). 

- `num_samples`: number of samples *per class*
- `num_features`$={\color{Tomato}J}$: number of features (excluding bias) - entries of the feature vector $\mathbf{\color{Dandelion}x}$
- `num_classes`: number of class labels - entries of the class label vector $\mathbf{\color{Dandelion}y}$
- `X(num_samples*num_classes, num_features)`: matrix ${\color{Brown}X}({\color{Tomato}N}, {\color{Tomato}J})$
  
${\color{Tomato}N}=$`num_samples*num_classes`

In [2]:
def init_toy_data(num_samples, num_features, num_classes, seed=3):
    # num_samples: number of samples *per class*
    # num_features: number of features (excluding bias)
    # num_classes: number of class labels
    # seed: random seed
    np.random.seed(seed)
    X=np.zeros((num_samples*num_classes, num_features))
    Y=np.zeros(num_samples*num_classes)
    for c in range(num_classes):
        # initialize multivariate normal distribution for this class:
        # choose a mean for each feature
        means = uniform(low=-10, high=10, size=num_features)
        # choose a variance for each feature
        var = uniform(low=1.0, high=5, size=num_features)
        # for simplicity, all features are uncorrelated (covariance between any two features is 0)
        cov = var * np.eye(num_features)
        # draw samples from normal distribution
        X[num_samples*c:num_samples*(c+1),:] = multivariate_normal(means, cov, size=num_samples)
        # set label
        Y[num_samples*c:num_samples*(c+1)] = c
    return X, Y

In [3]:
# create toy data
X, Y = init_toy_data(2, 4, 3) # 2 samples per class; 4 features, 3 classes
# Normalize data
X = zscore(X, axis=0)
print('X: ' + str(X))
print('Y: ' + str(Y))

X: [[ 0.39636145  1.09468144 -0.89360845  0.91815536]
 [ 0.94419323 -0.94027869  1.22268078  1.29597409]
 [-1.41577399  1.15477931 -0.62099631  0.08323307]
 [-1.35264614 -0.13598976 -1.14221784  0.26928935]
 [ 0.9352123   0.38225626  1.419864   -1.51152157]
 [ 0.49265316 -1.55544856  0.01427781 -1.0551303 ]]
Y: [0. 0. 1. 1. 2. 2.]


### Helper function `init_model(input_size, hidden_size, num_classes, seed=3)`

We now initialise our <b style="color:lightgreen">neural network</b> with one hidden layer consisting of $10$ units and and an output layer consisting of $3$ units. Here we expect (any number of) training samples with $4$ features. We do not apply any activation functions yet. The following figure shows a graphical representation of this neuronal net. 

<img src="nn.graphviz.png"  width="20%" height="20%">

- `input size`: number of input features - entries of the feature vector $\mathbf{\color{Dandelion}x}$
- `hidden_size`: number of units in the hidden layer
- `num_classes`: number of class labels, i.e., number of output units - entries of the class label vector $\mathbf{\color{Dandelion}y}$
- `model`: a dictionary of the weight matrices and the bias

In [6]:
#s = np.random.uniform(-1,1,10)
#print(s)

In [4]:
def init_model(input_size, hidden_size, num_classes, seed=3):
    # input size: number of input features
    # hidden_size: number of units in the hidden layer
    # num_classes: number of class labels, i.e., number of output units
    np.random.seed(seed)
    # Model defined as dictionary
    model = {}
    # initialize weight matrices and biases randomly
    model['W1'] = uniform(low=-1, high=1, size=(input_size, hidden_size))
    model['b1'] = uniform(low=-1, high=1, size=hidden_size)
    model['W2'] = uniform(low=-1, high=1, size=(hidden_size, num_classes))
    model['b2'] = uniform(low=-1, high=1, size=num_classes)
    return model

In [5]:
# initialize model
model = init_model(input_size=4, hidden_size=10, num_classes=3)

print('model: ' + str(model))
print('model[\'W1\'].shape: ' + str(model['W1'].shape))
print('model[\'b1\'].shape: ' + str(model['b1'].shape))
print('model[\'W2\'].shape: ' + str(model['W2'].shape))
print('model[\'b12\'].shape: ' + str(model['b2'].shape))
print('number of parameters: ' + str((model['W1'].shape[0] * model['W1'].shape[1]) + 
     np.sum(model['W2'].shape[0] * model['W2'].shape[1]) + 
     np.sum(model['b1'].shape[0]) +
     np.sum(model['b2'].shape[0] )))

model: {'W1': array([[ 0.10159581,  0.41629565, -0.41819052,  0.02165521,  0.78589391,
         0.79258618, -0.74882938, -0.58551424, -0.89706559, -0.11838031],
       [-0.94024758, -0.08633355,  0.2982881 , -0.44302543,  0.3525098 ,
         0.18172563, -0.95203624,  0.11770818, -0.48149511, -0.16979761],
       [-0.43294984,  0.38627584, -0.11909256, -0.68626452,  0.08929804,
         0.56062953, -0.38727294, -0.55608423, -0.22405748,  0.8727673 ],
       [ 0.95199084,  0.34476735,  0.80566822,  0.69150174, -0.24401192,
        -0.81556598,  0.30682181,  0.11568152, -0.27687047, -0.54989099]]), 'b1': array([-0.18696017, -0.0621195 , -0.46152884, -0.41641445, -0.0846272 ,
        0.72106783,  0.17250581, -0.43302428, -0.44404499, -0.09075585]), 'W2': array([[-0.58917931, -0.59724258,  0.02807012],
       [-0.82554126, -0.03282894, -0.27564758],
       [ 0.41537324,  0.49349245,  0.38218584],
       [ 0.37836083, -0.25279975,  0.33626961],
       [-0.32030267,  0.14558774, -0.34838568]

## <a name=task1> Exercise 1: Implement softmax layer </a>
Implement the <b style="color:cornflowerblue">softmax function</b>`softmax(X)` given by 

$$
\mathrm{\color{cornflowerblue}softmax}({\color{Dandelion}x}_{\color{VioletRed}i}) = \frac{e^{{\color{Dandelion}x}_{\color{VioletRed}i}}}{{\mathop{\color{CornflowerBlue}\sum}_{{\color{VioletRed}j}\in 1...{\color{Tomato}J}}e^{{\color{Dandelion}x}_{\color{VioletRed}j}}}}\,,
$$

where ${\color{Chocolate}J}$ is the total number of classes, so the length of  ${\color{Dandelion}\mathbf{x}}$ .

Note: Implement the function such that it takes a matrix ${\color{Cornflowerblue}X}$ of shape $({\color{Tomato}N}, {\color{Tomato}J})$ as input rather than a single instance ${\color{Dandelion}\mathbf{x}}$; ${\color{Tomato}N}$ is the number of instances.

In [6]:
def softmax(X):
    result=np.zeros((X.shape[0], X.shape[1]))
    #print(result)
    for m in range(X.shape[0]):
        for i in range(X.shape[1]):
            #print(m,i)
            #print(X[m,i])
            #print('-')
            if i==0:
                sum=0
                for j in range(X.shape[1]):
                    #print(m,j)
                    #print(X[m,j])
                    #print('-')
                    sum=sum+np.exp(X[m,j])
            result[m,i]=(np.exp(X[m,i])/sum)
    return result

In [30]:
#print(X[0,:])
#print(X.shape[0])

Check if everything is correct.

In [8]:
#XX = np.array([[0.1, 0.7, 0.23],[0.7, 0.4, 0.56]])
XX = np.array([[0.1, 0.7],[0.7, 0.4]])
exact_softmax = np.array([[ 0.35434369,  0.64565631],
                         [ 0.57444252,  0.42555748]])
#print(XX[1,2])
sm = softmax(XX)

#print(sm)
difference = np.sum(np.abs(exact_softmax - sm))
try:
    assert difference < 0.000001   
    print("Testing successful.")
except:
    print("Tests failed.")

Testing successful.


## <b>Exercise 2</b>: Implement the forward propagation algorithm for the model defined above.

The <b style="color:cornflowerblue">activation function</b> of the hidden neurons is a <b style="color:cornflowerblue">Rectified Linear Unit</b> `relu(x)`$=\mathrm{\color{cornflowerblue}max}(0, {\color{Dandelion}x})$ (to be applied element-wise to the hidden units)
The <b style="color:cornflowerblue">activation function</b> of the output layer is a <b style="color:cornflowerblue">softmax function</b> as (as implemented in [Exercise 1](task1)).

The function should return both the activation of the hidden units (after having applied the `relu` <b style="color:cornflowerblue">activation function</b>) (shape: $({\color{Tomato}N},$ `num_hidden`)) and the softmax model output (shape: $({\color{Tomato}N},$ `num_classes`)). 

Hiddenlayer function is linear:


Outputlayer function is the softmax function for probabilities. 

In [63]:
def forward_prop(X, model):
    W1=model['W1'] # theta for first layer
    b1=model['b1'] # theta_0 bias for first layer
    W2=model['W2'] # theta for hidden layer
    b2=model['b2'] # theta_0 bias for hidden layer
    #x_1=theta*X+theta_0
    #x_2=softmax(X)
    firstlayer=np.zeros((X.shape[0], b1.shape[0]))
    hidden_activations=np.zeros((X.shape[0], b2.shape[0]))
    probs=np.zeros((b2.shape[0], X.shape[1]))
    for m in range(X.shape[0]):
        #print(firstlayer)
        #print(hidden_activations)
        firstlayer[m]=np.dot(W1.T, X[m,:])+b1 #x_1
        hidden_activations[m]=np.dot(W2.T, firstlayer[m])+b2 # x_2
    probs=softmax(hidden_activations)
    print(probs)
    return hidden_activations, probs

In [64]:
acts, probs = forward_prop(X, model)
correct_probs = np.array([[0.22836388, 0.51816433, 0.25347179],
                            [0.15853289, 0.33057078, 0.51089632],
                            [0.40710319, 0.41765056, 0.17524624],
                            [0.85151353, 0.03656425, 0.11192222],
                            [0.66016592, 0.19839791, 0.14143618],
                            [0.70362036, 0.08667923, 0.20970041]])

# the difference should be very small.
difference =  np.sum(np.abs(probs - correct_probs))

try:
    assert probs.shape==(X.shape[0],len(set(Y)))
    assert difference < 0.00001   
    print("Testing successful.")
except:
    print("Tests failed.")

[[0.02860799 0.72168744 0.24970457]
 [0.02815474 0.21559875 0.75624651]
 [0.51480197 0.38142659 0.10377143]
 [0.83774096 0.02534048 0.13691856]
 [0.01346719 0.96908424 0.01744856]
 [0.64124853 0.072682   0.28606947]]
Tests failed.


## <b>Exercise 3:</b> 

How would you train the above defined neural network? Which loss-function would you use? You do not need to implement this.

# <b>Part 2 (Neural Net using Keras)</b>

Instead of implementing the model learning ourselves, we can use the neural network library Keras for Python (https://keras.io/). Keras is an abstraction layer that either builds on top of Theano or Google's Tensorflow. So please install Keras and Tensorflow/Theano for this lab.

## <b>Exercise 4:</b> Implement the same model as above using Keras:
    
    ** 1 hidden layer à 10 units
    ** softmax output layer à three units
    ** 4 input features
    
Compile the model using categorical cross-entropy (also referred to as 'softmax-loss') as loss function and using categorical crossentropy together with categorical accuracy as metrics for runtime evaluation during training.

Hint 1: Use the Sequential Class API of Keras (https://keras.io/api/models/sequential/ or https://www.tensorflow.org/guide/keras/sequential_model)

Hint 2: You can use the Adam optimizer of Keras for the model compilation

In [ ]:
from keras.models import Sequential
from keras.layers.core import Dense
from keras.layers.core import Activation

# define the model 
################################################
# INSERT YOUR CODE HERE                        #
################################################


# compile the model
################################################
# INSERT YOUR CODE HERE                        #
################################################

The description of the current network can always be looked at via the summary method. The layers can be accessed via model.layers and weights can be obtained with the method get_weights. Check if your model is as expected. 

In [ ]:
# Check model architecture and initial weights.

W_1, b_1 = model.layers[0].get_weights()
print("First layer weights: %s; shape: %s" % (W_1,W_1.shape))
print("First layer bias: %s; shape: %s" % (b_1,b_1.shape))
W_2, b_2 = model.layers[1].get_weights()
print("Second layer weights: %s; shape: %s" % (W_2,W_2.shape))
print("Second layer bias: %s; shape: %s" % (b_2,b_2.shape))
print("number of layes: " + str(len(model.layers)))
model.summary()


## <b>Exercise 5:</b> Train the model on the toy data set generated below: 

Hints: 

* Keras expects one-hot-coded labels 

* Don't forget to normalize the data

In [ ]:
from sklearn.model_selection import train_test_split

X, y = init_toy_data(1000,4,3, seed=3)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=67)

##################################
# INSERT YOUR CODE HERE          #
##################################

Compare the test accuracy with the train accuracy. What can you see? Is the model performing well?